### ISSUE TITLE
Can't delete a draft that you haven't saved

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#127]
This works

- Create a draft
- Save it
- Press delete

This doesn't

- Create a draft
- Press delete

**Comment by WebsByTodd** [comment]
What do you expect to happen? When an unsaved draft is deleted, the user is alerted that this can't be undone. If the user presses OK then the contents of the take editor are cleared. There is no need to interact with the server in the second case, so nothing is sent.

**Comment by nedtwigg** [comment]
To go back to the "Drafts" page, rather than to keep looking at the draft that I supposedly deleted.  Also, the "drafts" page should have a "New Draft" button.

**Comment by WebsByTodd** [comment]
That works well except when users aren't logged in. They press delete and because /drafts is only accessible to logged-in users they are shown the login page with the message "We can show that to you after you log in." It's a bit misleading.

We can easily change that message in this specific case or redirect users who aren't logged in somewhere else. Thoughts?

**Comment by nedtwigg** [comment]
Maybe "delete" should effectively be "back" for non-logged-in users?  Can we click the back button for them?

**Comment by nedtwigg** [comment]
Fixed by @WebsByTodd
