### ISSUE TITLE
Header design at desktop size

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#167]
Finally got everything merged in 👍 This needs a second pass.

<img width="807" alt="screen shot 2018-03-11 at 6 39 57 pm" src="https://user-images.githubusercontent.com/2924992/37261738-13dd47e8-255c-11e8-8d68-82899f861202.png">

**Comment by nedtwigg** [comment]
Take a look at the visual design of the footer at the same time.

**Comment by WebsByTodd** [comment]
So this is a tricky one. The left edge of the text in the footer is the same as the left edge of the icons in the nav menu, which is what I intended to do. If I bring the nav menu border in so that it aligns with the page/footer text, then the nav menu icons/text float by themselves. Another option is to extend the horizontal line above the footer out to match the length of the nav menu, which might achieve the consistent visual flow.

Thoughts?

**Comment by nedtwigg** [comment]
Btw, while the header is being redesigned, go ahead and put the search bar in.  When a user searches, send them to the Foundation with a message "We haven't implemented this yet!  Help us finish it [on GitHub](https://github.com/mytakedotorg/mytakedotorg/projects/3)"

**Comment by nedtwigg** [comment]
Big redesign merged in #171
