### ISSUE TITLE
Transcript numbers

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#191]
21.5% vs twenty-one and a half percent
$4 trillion vs four trillion dollars vs $4,000,000,000,000
four score and seven vs 87   ;-)

When I did the 1960 debate, I turned everything into words.  After doing a little of some of the 1992 debates, it seems there are now more numbers.  I think I'm kinda leaning towards every number being an actual number.  Might be interesting to look at every number between one million and two million in a debate,   vs between one billion and two billion, vs between one trillion and two trillion.

I also think it's maybe easier for people to compare $4,000,000,000,000 and $4,000,000, as compared to $4 trillion vs $4 million.  Obviously trillion is more than a million, but writing it out seems perhaps more plain.

Whaddya think @WebsByTodd  @hattersv?

**Comment by WebsByTodd** [comment]
I've seen some patterns in transcripts where numbers one through nine are spelled out and numbers 10 and up are numbers, but I don't think I've been consistent in following them. Some of my thoughts:

- $4 trillion seems much more popular than $4,000,000,000,000. This is the convention I've been following lately. I have not been spelling out "dollars".
- Decimals in numbers can be confused as periods at the ends of sentences, so I lean towards spelling out "two-thirds" or "and a half".
- I don't have an opinion on spelling out numbers, but I think we should have a clear convention. For example, if we spell out one through nine and use numerals for everything greater than that then we can tell our search tools to look for "one" whenever "1" or "one" is searched.

There are also language choices. What if a speaker is talking in general terms "somewhere around a billion dollars" or "another billion dollars"? I've seen the conventions falter in situations like these as well.

**Comment by WebsByTodd** [comment]
I like to summarize things, so here are the takeaways from that link:
- Spell out whole numbers up to (and including) nine (e.g., zero, one, 10, 96, 104).
- Spell out casual expressions (e.g., A picture is worth a thousand words, but a really good one is worth a thousand dollars).
- Spell out numbers that begin a sentence unless it begins with a year (e.g., Twelve drummers, The 10 lords a-leaping, 2011’s quota for off-season holiday references has been filled).
  - There is no "and" when you spell out whole numbers (e.g., one hundred one Dalmatians, not one hundred and one Dalmatians).
- Spell out ordinal numbers up to (and including) ninth when indicating sequence in time or location (e.g., first kiss, 11th hour) but not when indicating sequence in naming conventions (usually geographic, military, or political, e.g., 9th U.S. Circuit Court of Appeals).

There's nothing about money though. I've personally been using numerals for all dollar amounts so that I can use the dollar sign instead of the word "dollars". Also I've been spelling out "million", "billion", and "trillion". (e.g., "$100 billion", "$10,000"). Any thoughts here?

**Comment by nedtwigg** [comment]
- The cost could be 100 or 200 dollars!
- The cost could be 100 dollars or 200 dollars!
- The cost could be $100 or $200!
- The cost could be 100 or 200 percent!
- The cost could be 100 percent or 200 percent!
- The cost could be 100% or 200%!

I think "$" and "%" read better, but spelling out "dollars" and "percent" matches the transcript timestamps better.  Leading dollar signs aren't handled correctly by the parser right now either, but that's very fixable.  Overall, I lean towards the accuracy and ease-of-parsing of spelling them out, but it'd be very easy to convince me the other way.

**Comment by WebsByTodd** [comment]
Based on your points, I agree with spelling out the words instead of using symbols.
